=== SeabassTheFish03/TheoryViz/schema/dfa.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "./schema/dfa.schema.json",
	"title": "DFA", 
	"type": "object",
	"properties": {
		"fa_type": {"const": "dfa"},
		"states": {
			"type": "array",
			"items": {"type": "string"},
			"minItems": 1,
			"uniqueItems": true
		},
		"input_symbols": {
			"type": "array",
			"items": {"type": "string"},
			"minItems": 1,
			"uniqueItems": true
		},
		"transitions": {"type": "object"},
		"initial_state": {"type": "string"},
		"final_states": {
			"type": "array",
			"items": {"type": "string"},
			"minItems": 1,
			"uniqueItems": true
		},
		"allow_partial": {"type": "boolean"}
	},
	"required": ["fa_type", "states", "input_symbols", "transitions", "initial_state", "final_states"]
}

=== SeabassTheFish03/TheoryViz/fa_vault/testing/dfa_six_input_characters.json
{
	"fa_type": "dfa",
	"states": ["1", "2"],
	"input_symbols": ["a", "b", "c", "d", "e", "f"],
	"transitions": {
		"1": {"a": "2", "b": "2", "c": "1", "d": "2", "e": "1", "f": "2"},
		"2": {"a": "2", "b": "1", "c": "2", "d": "1", "e": "2", "f": "1"}
	},
	"initial_state": "1",
	"final_states": ["2"]
}

=== SeabassTheFish03/TheoryViz/fa_vault/testing/dfa_15_states.json
{
	"fa_type": "dfa",
	"states": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"],
	"input_symbols": ["a"],
	"transitions": {
		"1": {"a": "2"},
		"2": {"a": "3"},
		"3": {"a": "4"},
		"4": {"a": "5"},
        "5": {"a": "6"},
        "6": {"a": "7"},
        "7": {"a": "8"},
        "8": {"a": "9"},
        "9": {"a": "10"},
        "10": {"a": "11"},
        "11": {"a": "12"},
        "12": {"a": "13"},
        "13": {"a": "14"},
        "14": {"a": "15"},
        "15": {"a": "1"}
	},
	"initial_state": "1",
	"final_states": ["15"]
}

=== SeabassTheFish03/TheoryViz/fa_vault/dfaDemo.json
{"fa_type": "dfa", "states": ["N", "P", "D"], "input_symbols": ["a", "b", "c", "d", "e"], "transitions": {"N": {"a": "P", "b": "P", "c": "D", "d": "D", "e": "D"}, "P": {"a": "D", "b": "D", "c": "N", "d": "N", "e": "N"}, "D": {"a": "D", "b": "D", "c": "D", "d": "D", "e": "D"}}, "initial_state": "N", "final_states": ["P"]}
