=== SeabassTheFish03/TheoryViz/schema/tm.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "./schema/tm.schema.json",
	"title": "TM",
	"type": "object",
	"properties": {
		"fa_type": {"const": "tm"},
		"states": {
			"type": "array",
			"items": {"type": "string"},
			"minItems": 1,
			"uniqueItems": true
		},
		"tape_symbols": {
			"type": "array",
			"items": {"type": "string"},
			"minItems": 1,
			"uniqueItems": true
		},
		"input_symbols": {
			"type": "array",
			"items": {"type": "string"},
			"minItems": 1,
			"uniqueItems": true
		},
		"transitions": {"type": "object"},
		"initial_state": {"type": "string"},
		"blank_symbol": {"type": "string"},
		"final_states": {
			"type": "array",
			"items": {"type": "string"},
			"minItems": 1,
			"uniqueItems": true
		},
		"allow_partial": {"type": "boolean"}
	},
	"required": ["fa_type", "states", "tape_symbols", "transitions", "initial_state", "final_states", "blank_symbol"]
}

=== SeabassTheFish03/TheoryViz/fa_vault/testing/tm_incomplete_transition.json
{
	"fa_type": "tm",
    "states": ["1", "2", "3"],
    "tape_symbols": ["a", "b", "c"],
    "transitions": {
        "1": {"a": "2", "b": "2", "c": "1"},
		"2": {"a": "3", "b": "3", "c": "2"},
		"3": {"a": "1", "b": "3"}
    },
    "initial_state": "1",
	"blank_symbol": "X",
	"final_states": ["3"]
}

=== SeabassTheFish03/TheoryViz/fa_vault/testing/tm_missingTransition.json
{
	"fa_type": "tm",
    "states": ["q0", "q1", "q2"],
    "tape_symbols": ["0", "1", "x", "y", "."],
    "input_symbols": ["0", "1"],
    "transitions": {
        "q0": {
            "0": ["q1","x", "R"],
            "1": ["q2", "y", "R"]
        },
	    "q2": {
	        "0": ["q2", "0", "L"],
	        "x": ["q0", "x", "R"],
	        "y": ["q2", "y", "L"]
        }
    },
    "initial_state": "q0",
	"blank_symbol": ".",
	"final_states": ["q2"]
}
